[package]
name = "brotli-wasm"
version = "1.0.0"
description = "A compressor and decompressor for Brotli that actually works, for node & browsers"
authors = ["Tim Perry <tim@httptoolkit.tech>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"